---
title: "data-sorting"
author: "Cole Henry"
date: "2023-01-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# data scraping from pro football reference
install.packages('rvest')
library(rvest)

simple <- read_html("https://www.pro-football-reference.com/years/2022/opp.htm") %>%
  html_nodes(".table_wrapper") %>%
  html_text()

library(readr)
main <- parse_number(simple)

simple
```

```{r, show_col_types = FALSE}
#reading in data
library(readr)
X2022TeamDefense <- read_csv("2022TeamDefense.csv")
X2022PassingDefense <- read_csv("2022PassingDefense.csv")
X2022RushingDefense <- read_csv("2022RushingDefens.csv")
X2022Advanced <-read_csv("2022AdvancedDefense.csv")

#removing un-needed avg rows
X2022PassingDefense <- X2022PassingDefense[-c(33:35),]
X2022TeamDefense <- X2022TeamDefense[-c(33:35),]

#from espn 2022FFL
TotFantasyPts <- c(158,102,122,120,102,105,87,153,138,97,78,106,102,98,84,100,173,32,115,97,156,89,94,91,69,129,89,111,55,64,71,80)
X2022PassingDefense <- cbind(X2022PassingDefense,TotFantasyPts)
X2022PassingDefense <- as.data.frame(X2022PassingDefense)

colnames(X2022PassingDefense)[3] <- "GamesPlayed"

X2022PassingDefense <- transform(X2022PassingDefense, FantasyPPG = TotFantasyPts / GamesPlayed)

#vector of team names in order we want
TeamOrderPassing <- X2022PassingDefense[,2]
#TeamOrderRushing <-

#sorting the other dataset to have the teams in the right order
X2022TeamDefenseSorted <- X2022TeamDefense[match(TeamOrderPassing,X2022TeamDefense$Tm), ]
X2022TeamDefenseSorted <- as.data.frame(X2022TeamDefenseSorted)
X2022TeamDefenseSorted <-cbind(X2022TeamDefenseSorted, FantasyPPG = X2022PassingDefense[,27])
X2022TeamDefenseSorted <- as.data.frame(X2022TeamDefenseSorted)



#checking correlation between all numeric vars
#cor(X2022TeamDefenseSorted[,unlist(lapply(X2022TeamDefenseSorted, is.numeric))],X2022TeamDefenseSorted$TotFantasyPoints)
```

```{r}
#RUSHING CLEANUP
X2022RushingDefense <- transform(X2022RushingDefense, 'TD/G'= X2022RushingDefense$TD / X2022RushingDefense$G) 
X2022RushingDefense <- X2022RushingDefense[,-c(1,3:6,9)]
X2022RushingDefense <- as.data.frame(X2022RushingDefense)
colnames(X2022RushingDefense) <- c('Tm', 'RushingYards.Att','RushingYards.Game', 'RushingTD.Game')

X2022TeamDefenseSorted <- X2022TeamDefense[match(TeamOrderPassing,X2022TeamDefense$Tm), ]

```

```{r}
#PASSING CLEANUP
X2022PassingDefense <- transform(X2022PassingDefense, 'PassingYDS.G'= Yds / GamesPlayed) 
X2022PassingDefense <- transform(X2022PassingDefense, 'PassingTDs.G'= TD / GamesPlayed) 
X2022PassingDefense <- transform(X2022PassingDefense, 'Tackles4Loss.G'= TacklesForLoss / GamesPlayed) 
X2022PassingDefense <- transform(X2022PassingDefense, 'QBHits.G'= QBHits / GamesPlayed) 

X2022PassingDefense <- X2022PassingDefense[,-c(1,3:5,7:8,10:11,13:14,16,18:21,25:26)]
```

```{r}
#ADVANCED CLEANUP
X2022Advanced <- X2022Advanced[,-c(2:6,8:10,12,14,16:17,19)]
```

```{r}
#COMBINING
defenseFull <- X2022RushingDefense[match(TeamOrderPassing,X2022RushingDefense$Tm), ]

defenseFull <- cbind(defenseFull, X2022PassingDefense[match(TeamOrderPassing,X2022PassingDefense$Tm), ])

defenseFull <- cbind(defenseFull, X2022Advanced[match(TeamOrderPassing,X2022Advanced$Tm), ])

defenseFull <- as.data.frame(defenseFull)

defenseFull <- defenseFull[,-c(5,19)]

defenseFull <- cbind(defenseFull[,-c(13)],'AvgFantasyPoints' = defenseFull[,13])
```





